[package]
name = "rbw"
version = "0.4.6"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

description = "Unofficial Bitwarden CLI"
repository = "https://git.tozt.net/rbw"
readme = "README.md"
keywords = ["bitwarden"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT"

[dependencies]
aes = "0.4"
anyhow = "1.0"
arrayvec = "0.5"
async-trait = "0.1"
base64 = "0.12"
block-modes = "0.4"
chbs = "0.0.10"
daemonize = "0.4"
directories = "3.0"
env_logger = "0.7"
humantime = "2.0"
libc = "0.2"
log = "0.4"
nix = "0.17"
openssl = "0.10"
paw = "1.0"
percent-encoding = "2.1"
rand = "0.7"
region = "2.2"
reqwest = { version = "0.10", features = ["blocking", "json"] }
ring = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"
snafu = "0.6"
structopt = { version = "0.3", features = ["paw", "wrap_help"] }
tempfile = "3.1"
term_size = "0.3"
textwrap = "0.11"
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
zeroize = "1.1"
keyring = { version = "0.9.0" }

[package.metadata.deb]
depends = "pinentry"
license-file = ["LICENSE"]

[features]
default = []
#keychain = ["keyring"]
